name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.17.6'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn workspaces run test
